apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.kdynaroll.env.metricsBindPort }}
    targetPort: {{ .Values.kdynaroll.env.metricsBindPort }}
